---
metadata:
  created_by: "munki-mscp-generator"
  creation_date: "today"
version: 1.0
static_fields:
  category: "Compliance"
  installer_type: "nopkg"
  unattended_install: True
fields_from_rule:
  display_name: "title"
  description: "discussion"






