---
fields_from_rule:
  display_name: "title"
  description: "discussion"
static_fields:
  category: "Compliance"
  installer_type : "nopkg"
metadata:
  created_by: "munki-mscp-generator"
  creation_date: "today"